### ISSUE TITLE
add search feature

### ISSUE THREAD

**Issue by tscibilia** [hubot-scripts/hubot-trello#4]
implement the command --> hubot trello search "query"
https://trello.com/docs/api/search/

**Comment by syntax922** [comment]
I'm going to be looking into adding this feature tonight. I'm envisioning probably 2 searches. 
- One for cards you're a member of (Trello My Cards)
- One for cards matching your search criteria

It's my understanding from the API that a user will be able to modify the search directly without additional scripting if the user passes the expected modifying parameters. So we don't need to build additional search methods.

Please let me know if this makes sense for what you're looking for.

**Comment by tscibilia** [comment]
Yeah, that would be perfect!

**Comment by syntax922** [comment]
Sorry I've been slow on this @tscibilia I'm hoping that tonight I'll have more time to begin work on this!

**Comment by syntax922** [comment]
@tscibilia thought I'd give an update. I've successfully added a feature for "<botname> trello get <user's first name>'s cards. I'm struggling right now with the get my cards because the hubot is it's own user so it can't use the "me parameter" and I've not yet found the command for getting a user's first name from the adapter. (I'm sure it's msg.message.user.<something> just haven't found it yet)

Because we're currently working with a global variable for what board we're dealing with that's been locked in appropriately (but can be changed if the whole feature is considered for multiple boards down the road)

Next up is pass your own search criteria (should be simple enough now)

**Comment by syntax922** [comment]
I've updated my master and it's now included in the PR. Right now I'm only returning cards but the criteria you pass can use all of the functionality trello has built into their search. Let me know how this works out.

**Comment by codeimpossible** [comment]
Going to close this since search has shipped in v0.2.0.
