### ISSUE TITLE
How can I add a new list?

### ISSUE THREAD

**Issue by dylanh724** [hubot-scripts/hubot-trello#9]
Forgive my newbness, but can you make a new card yet within a board, or am I bugging out?

**Comment by syntax922** [comment]
@dylanh724 per our conversation this issue is actually about wanting the ability to create a new list on a board. 

Indeed this functionality is _not_ present in the current commit. However, I can work to add this functionality! I've already done a PR (Pull Request) to add other functionality to this fork, and I'm hoping that @codeimpossible will be able to accept that PR and put it out for npm. 

Does something like "Trello Create List "**List Name**"" make sense as the keyword for this functionality? I'm envisioning the conversation goes something like:

> Hubot Create List "Things To Do"
> "That list has been created"
> Hubot add "Things to Do" My Development Work
> "Ok I've created that card [link goes here]"
> Hubot description [card] "I'm going to be doing a lot of work with this card"
> "Ok I've updated that card"

**Comment by dylanh724** [comment]
Wonderful :)

**Comment by syntax922** [comment]
@dylanh724 Just a quick update. I have this functionality written but have been unable to test. Had a server crash on me that I've been rebuilding. Hoping to test this week and make another PR.

**Comment by syntax922** [comment]
@dylanh724 I believe this issue can be marked as resolved. Please let me know if you're looking for something else or if you have any other issues.

@codeimpossible I'm finishing up some work with relating cards and then am considering testing the waters on some webhooks for notifications. Anything you'd like me to be taking a look at?

**Comment by codeimpossible** [comment]
Going to close this issue since @syntax922 added the ability to create a list.

@syntax922 maybe continue with #10 in the meantime, unless you get more ideas for features. Really appreciate all the work you've put into this!
